### ISSUE TITLE
Wrapping async functions in promises

### ISSUE THREAD

**Issue by yortus** [selfrefactor/awaited#1]
Firstly, as per my comments on reddit, async functions can be exported as-is without needing to wrap them in another function.

Aside from that, I just wanted to mention that you can simplify your wrapper function template if you wish:

From the template in your `main.js`:

```js
function ${keyword}(${input}){
    return new Promise((resolve, reject)=>{
        let result = ${keyword}Async(${input})
        if(result===null){
            reject("error coming from ${keyword}")
        }else{
            resolve(result)
        }
    })
}
```

You could use the much shorter version:

```js
function ${keyword}(${input}){
    return ${keyword}Async(${input});
}
```

The async function already returns a promise, so you can just return that. No need to create a new one.

**Comment by selfrefactor** [comment]
I will try that and get back with the result.

**Comment by selfrefactor** [comment]
The proposal was tested and it worked just fine.

My wrapper function's goal is to act as a buffer and to handle any errors coming from the **async** function. 

But it makes sense to set an API method which will integrate your code, and this method will be perfect when the **async** functions awaits **Promises**, where one know there is no **reject/catch** flow. 

I will leave the issue opened, until this API is created.

**Comment by yortus** [comment]
Just FYI, async functions never throw and they never return `null`. So there's no point checking for `result === null` or using a `try/catch` block. They always return an ES6 `Promise` instance. If an exception is thrown in the body of the async function, then the promise it returned will be rejected.

That's why I suggest using the shorter version, because the other checks are never required, and in fact your `reject("error coming from ${keyword}")` line will never be executed under any circumstances.

**Comment by selfrefactor** [comment]
Ok, I will use it on **main** method then. 
But, before we all move on to more important matters, can you just comment the following code from async/await proposal in regards to your comment "there's no point of try/catch block"

```
async function chainAnimationsAsync(elem, animations) {
        let ret = null;
        try {
            for(const anim of animations) {
                ret = await anim(elem);
            }
        } catch(e) { /* ignore and keep going */ }
        return ret;
    }
```  

I place try/catch because of the await part, exactly as the proposal suggest. 
Am I missing something?

**Comment by yortus** [comment]
Errors can be thrown *inside* an async function, such as at an `await` expression, so `try/catch` can make sense there, like in the example you just gave.

I was meaning that there's no need to put a `try/catch` around a simple call to an async function, since such a call will never throw (it will indicate failure by rejecting its returned promise).

**Comment by selfrefactor** [comment]
I see it better now, thank you for the detailed explanation.

 I am closing the issue as I accept your arguments and your suggestion is already in the library. 

I mention you at the end, despite you deserve much higher recognition.
